# # v1
# name: Publish Docker Image
# on: [push]
# jobs:
#   push_to_registry:
#     name: Push Docker Image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check Out Repo
#         uses: actions/checkout@v2
#       - name: Push to Docker Hub
#         uses: docker/build-push-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           repository: raeganbarker/marduk
#           tag_with_ref: true

# v2
name: Publish Docker Image
on: [push]
jobs:

  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log In to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          tags: raeganbarker/marduk:latest

  run_pytests:
    name: Run Automated Tests
    needs: push_to_registry
    runs-on: ubuntu-latest
    container:
      image: raeganbarker/marduk:latest
      credentials:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check Directory
        run: |
          cd /app/marduk/
          ls -la
          cd pytests
          ls -la
      - name: Run Pytests
        run: |
          cd /app/marduk/pytests/
          python3 /app/marduk/pytests/runner.py
      - name: Publish Deliverable
        uses: actions/upload-artifact@v1
        with:
          name: test_results
          path: /app/marduk/pytests/auto_tests.xml


# Next step: https://towardsdatascience.com/speed-up-your-pytest-github-actions-with-docker-6b3a85b943f

# Next step (better?): https://stackoverflow.com/questions/58930529/github-action-how-do-i-run-commands-inside-a-docker-container

# Credentials: https://stackoverflow.com/questions/64033686/how-can-i-use-private-docker-image-in-github-actions


# Could just push a marduk:tests image with the command in it? That way don't
# have to do anything crazy to get the tests to run via actions?
# But what about surfacing the deliverable?
# Can GitHub just get that as an artifact for me from the volume by referencing
# the filesystem path?

# Progress: Figured out how to publish an image.
# Next: Figure out how to retrieve the image.
# Next: Figure out how to issue commands to a container from the image.
# Next: Figure out how to retrieve an artifact from the image.
