name: Build & Publish Docker Image
on:
  pull_request:
    types: [closed]
jobs:
  push_image_to_docker_hub:
    # if: github.event.pull_request.merged == true
    if: github.event.pull_request.merged
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Current Repo # marduk
        uses: actions/checkout@v2
      - name: Set Up Docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Log In to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: raeganbarker/marduk:test
          file: docker/Dockerfile.test


# This next one is a bit of a workaround as it assumes the only push to
# DEV will be from a valid PR from a feature branch.

# name: Build & Publish Docker Image
# on:
#   push:
#     branches:
#       - dev
# jobs:
#   push_image_to_docker_hub:
#     name: Push Docker Image to Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check Out Current Repo # marduk
#         uses: actions/checkout@v2
#       - name: Set Up Docker BuildX
#         uses: docker/setup-buildx-action@v1
#       - name: Log In to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build and Push Docker Image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: raeganbarker/marduk:test
#           file: docker/Dockerfile.test
