# name: Build, Publish, & Test Docker Image With Docker Compose
name: Test
on: [push]
jobs:
  check_stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Clean pwd + ls -la
        run: |
          pwd
          ls -la
      - name: Checkout marduk
        uses: actions/checkout@v2
      - name: Post-marduk checkout pwd + ls - la
        run: |
          pwd
          ls -la
      - name: Checkout baldur
        uses: actions/checkout@v2
        with:
          repository: "raegancbarker/baldur"
          ref: "example-docker-compose-intermediate"
          token: ${{ secrets.GH_TOKEN }}
      - name: Post-baldur checkout pwd + ls - la
        run: |
          pwd
          ls -la
          cd ..
          pwd
          ls - la
          cd ..
          pwd
          ls - la



  # push_image_to_docker_hub:
  #   name: Push Docker Image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check Out Repo
  #       uses: actions/checkout@v2
  #     - name: Set Up Docker BuildX
  #       uses: docker/setup-buildx-action@v1
  #     - name: Log In to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: true
  #         tags: raeganbarker/marduk:test
  #         file: docker/Dockerfile.test
  # run_tests_in_docker_compose:
  #   name: Run Tests in Docker Compose
  #   needs: push_image_to_docker_hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check Out Repo
  #       uses: actions/checkout@v2
  #     - name: Log In to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Run Docker Compose
  #       run: |
  #         docker-compose -f docker/docker-compose-test.yml up -d
  #     - name: Wait for Tests to Complete
  #       run: >
  #         while [ `docker inspect --format '{{json .State.Running}}' repo_container` = "true" ];
  #         do echo "Waiting for repo_container to exit...";
  #         docker ps;
  #         sleep 5;
  #         done
  #     - name: Copy Test Results from Container to Host
  #       run: |
  #         docker cp repo_container:/app/marduk/auto_tests.xml .
  #     - name: Upload Test Results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: test_results
  #         path: auto_tests.xml
  #     - name: Publish Test Results from Host to GitHub Workflow
  #       uses: EnricoMi/publish-unit-test-result-action@v1
  #       if: always()
  #       with:
  #         files: |
  #           auto_tests.xml
